# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Server CI

on:
  push:
    paths:
      - "server/**"
      - ".github/workflows/nodejs-server.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: './server/package.json'
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: "./server/pnpm-lock.yaml"
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Dependencies
      run: pnpm install
      
      working-directory: ./server
    - run: npm run build --if-present
      working-directory: ./server
